const products = [
  {
    id: 1,
    name: "Smartphone X12",
    prevPrice: 799,
    currPrice: 699,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZ0Mf-I1HKvUfKOmQ_A3FI_6YbWLDVu1CsfA&s",
  },
  {
    id: 2,
    name: "Laptop Pro 15",
    prevPrice: 1399,
    currPrice: 1299,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2eIy6oKwQ_jpvNr7jmyo0ZbUYEv_3v1EZJQ&s",
  },
  {
    id: 3,
    name: "Wireless Earbuds Z",
    prevPrice: 199,
    currPrice: 149,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjnJQi7uqNTauyCG4h16NASRkMvcq7v4ROHA&s",
  },
  {
    id: 4,
    name: 'Smart TV 50"',
    prevPrice: 899,
    currPrice: 799,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc_s3zzqY34zTBJeE1v4r-1SQhX8uMXD5mFw&s",
  },
  {
    id: 5,
    name: "Gaming Console 5",
    prevPrice: 599,
    currPrice: 499,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgp1FmaMM6hRjNT5QLgJcUwPVeJzIJctLg7Q&s",
  },
  {
    id: 6,
    name: "Bluetooth Speaker Mini",
    prevPrice: 129,
    currPrice: 99,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlhivcImoon9Uimi40v7EaguHw8CulI3C09g&s",
  },
  {
    id: 7,
    name: "4K Action Camera",
    prevPrice: 349,
    currPrice: 299,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7QjjDiBlRoWtHFm0SD5YzVFBU38NpmdqpeQ&s",
  },
  {
    id: 8,
    name: "Smartwatch Elite",
    prevPrice: 249,
    currPrice: 199,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSN5Ryt_lgOFDX5g3zufHQaYX5gJNJuXxDulg&s",
  },
  {
    id: 9,
    name: "Gaming Headset X",
    prevPrice: 129,
    currPrice: 89,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDR5iFW-FzLNuBQuFx2mE-tspPMtIgePmn_Q&s",
  },
  {
    id: 10,
    name: "External SSD 1TB",
    prevPrice: 199,
    currPrice: 149,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSBMwhoITT8ED4OXAH7yeRSQ2Ss9P8U1TxN_w&s",
  },
  {
    id: 11,
    name: "Drone Phantom",
    prevPrice: 999,
    currPrice: 899,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTb-FMX_NETS3WjnnRHAQ4BKW0uj114q_EXrQ&s",
  },
  {
    id: 12,
    name: "Digital Camera HD",
    prevPrice: 599,
    currPrice: 549,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSR5wWR3ZMX9_GiJqfsYTZKg_HcOwL3vruo6A&s",
  },
  {
    id: 13,
    name: "Portable Charger 20k",
    prevPrice: 79,
    currPrice: 59,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmTeSQirER040iFyK5YTRNoxSHbjdpMBuI4g&s",
  },
  {
    id: 14,
    name: "VR Headset Pro",
    prevPrice: 399,
    currPrice: 349,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnToT7Vn4t6L4LxGHBO05-Spkx1OhE1c14iA&s",
  },
  {
    id: 15,
    name: 'Tablet 10.1"',
    prevPrice: 449,
    currPrice: 399,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTR7OxPQA_4j6SWlkkSHOZDpL1t2v5kWp79jA&s",
  },
  {
    id: 16,
    name: "Wireless Keyboard",
    prevPrice: 69,
    currPrice: 49,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSov8x54210soKIFHfp75tzcfwCxMxuyoRBBw&s",
  },
  {
    id: 17,
    name: "Noise-Cancelling Headphones",
    prevPrice: 299,
    currPrice: 249,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRC0rJu-9tnWbEoQpLyuh_3RpfWekAjZ4iEeg&s",
  },
  {
    id: 18,
    name: "Smart Home Speaker",
    prevPrice: 159,
    currPrice: 129,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTR3hwylarHGKoxGbVrPfNBIZmmMIiVa38Z_g&s",
  },
  {
    id: 19,
    name: "Projector 1080p",
    prevPrice: 649,
    currPrice: 599,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRB3jbDWZy84Zv75fXab0OnKlupvoHxYYI9Rw&s",
  },
  {
    id: 20,
    name: "Fitness Tracker X",
    prevPrice: 99,
    currPrice: 79,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2z3jiM2BiYhzVYUV8d7Si4wTIbE1kowRMeQ&s",
  },
];

export default products;
